site_name: "MMG 2700: Foundations in R for Life Science"
site_description: "MMG 2700: Foundations in R for Life Science"
site_author: "Princess Rodriguez" 
#site_url: https://prodriguez19.github.io/MMG3320-5320/

theme:
  name: material
  
  features:
    - content.code.copy
    - content.code.annotate 
    - content.code.select
    - navigation.tabs
    - navigation.top
  
  palette: 

    # Palette toggle for light mode
    - scheme: default
      primary: teal
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: teal
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

nav:
  - Home:
      - Introduction: index.md
      - Syllabus: resources/MMG2700_Syllabus-fall-2026.pdf
  - Lessons: 
      - Week 1:
          - Overview: lessons/ch01/index.md

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.critic
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
plugins:
  - mkdocs-pdf
  - search

