site_name: "MMG 2700: Foundations in R Programming for Life Science"
site_description: "MMG 2700: Foundations in R Programming for Life Science"
site_author: "Princess Rodriguez" 
#site_url: https://prodriguez19.github.io/MMG3320-5320/

theme:
  name: material
  
  features:
    - content.code.copy
    - content.code.annotate 
    - content.code.select
    - navigation.tabs
    - navigation.top
  
  palette: 

    # Palette toggle for light mode
    - scheme: default
      primary: teal
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: teal
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

nav:
  - Home:
      - Introduction: index.md
      - Syllabus: resources/MMG2700_Syllabus-fall-2026.pdf
      - Schedule: schedule.md
      - Papers: resources/index.md
  - Lessons: 
      - Week 1:
          - Overview: lessons/ch01/index.md
          - Lesson 1: lessons/ch01/01_week1_mmg2700.md
          - Lesson 2: lessons/ch01/02_week1_mmg2700.md
      - Week 2:
          - Overview: lessons/ch02/index.md
          - Lesson 3: lessons/ch02/03_week2_mmg2700.md

      - Week 3:
          - Overview: lessons/ch03/index.md
          - Lesson 4: lessons/ch03/04_week3_mmg2700.md
          - Lesson 5: lessons/ch03/05_week3_mmg2700.md
      - Week 4:
          - Overview: lessons/ch04/index.md
          - Lesson 6: lessons/ch04/06_week4_mmg2700.md
          - Lesson 7: lessons/ch04/07_week4_mmg2700.md

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.critic
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
plugins:
  - mkdocs-pdf
  - search

